apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch-master
  namespace: monitoring
spec:
  version: 8.6.0
  http:
    service:
      metadata: null
  nodeSets:
    - config:
        node.roles:
          - master
          - data
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
            app: elasticsearch-master
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: 1
                limits:
                  memory: 4Gi
                  cpu: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      name: default
      count: 1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  auth:
    fileRealm:
      - secretName: kibana-user
