apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-datasource
  namespace: monitoring
spec:
  name: grafana-datasource.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      version: 1
      access: proxy
      editable: true
      isDefault: true
      url: 'http://prometheus-operator-kube-p-prometheus.monitoring.svc:9090'
      jsonData:
        timeInterval: 5s
